name: cams main workflow

on:
  push:
    branches:
    - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_API_URL: https://api.cryptonets.ultrapass.id/node
      REACT_APP_API_URL_WASM: https://api.cryptonets.ultrapass.id/node
      REACT_APP_API_ORCHESTRATION: https://api.orchestration.ultrapass.id
      REACT_APP_API_KEY: "0000000000000000test"
      GENERATE_SOURCEMAP: false
      REACT_APP_WASM_MODULE: face_mask
      REACT_APP_SENTRY_URL: https://88fc65fee23b4e68af4569038c7adbee@o4505141914501120.ingest.sentry.io/4505141916467200
      CI: false

    steps:
        - uses: actions/checkout@v1

        - name: Install dependencies
          run: yarn install

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET_PROD }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
            invalidation: / *
